# Generated by Django 4.2.5 on 2023-09-12 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('currency', models.CharField(choices=[('USDT', 'Usdt'), ('USD', 'Usd'), ('EURO', 'Euro')], default='USD', max_length=10, verbose_name='currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('deposit_time', models.IntegerField(verbose_name='Deposit_time')),
                ('interest', models.IntegerField(verbose_name='Interest')),
                ('state', models.CharField(choices=[('Success', 'Success'), ('Not_Accepted', 'Not Accepted'), ('Under_Review', 'Under Review')], default='Under_Review', max_length=50, verbose_name='State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('currency', models.CharField(choices=[('USDT', 'Usdt'), ('USD', 'Usd'), ('EURO', 'Euro')], default='USD', max_length=10, verbose_name='currency')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Loan_amount')),
                ('payment_time', models.IntegerField(verbose_name='Payment_time')),
                ('installment', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Installment')),
                ('state', models.CharField(choices=[('Success', 'Success'), ('Not_Accepted', 'Not Accepted'), ('Under_Review', 'Under Review')], default='Under_Review', max_length=50, verbose_name='State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('loan_wage', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Loan_wage')),
                ('transfer_wage', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Transfer_wage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('private_key', models.CharField(max_length=500, unique=True, verbose_name='private_key')),
                ('address', models.CharField(max_length=500, unique=True, verbose_name='address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
