# Generated by Django 4.2.5 on 2023-09-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_alter_createdeposit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeposit',
            name='interest',
            field=models.FloatField(verbose_name='Interest'),
        ),
    ]
