# Generated by Django 4.2.5 on 2023-09-12 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0005_fiatdeposithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('subject', models.CharField(choices=[('Card', 'Card'), ('Wallet', 'Wallet'), ('Transactions', 'Transactions'), ('Requests', 'Requests'), ('Digital_Sign', 'Digital Sign'), ('Transfer', 'Transfer'), ('Deposit', 'Deposit'), ('Profile', 'Profile'), ('Last_Price', 'Last Price')], max_length=20, verbose_name='Subject')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('state', models.CharField(choices=[('Success', 'Success'), ('Not_Accepted', 'Not Accepted'), ('Under_Review', 'Under Review')], default='Under_Review', max_length=50, verbose_name='State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
