# Generated by Django 4.2.4 on 2023-09-12 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0006_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('card_type', models.CharField(choices=[('Business_Card', 'Business Card'), ('Virtual_Card', 'Virtual Card')], max_length=20, verbose_name='Card_type')),
                ('card_level', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Normal', 'Normal')], max_length=20, verbose_name='Card_level')),
                ('currency', models.CharField(choices=[('USDT', 'Usdt'), ('USD', 'Usd'), ('EURO', 'Euro')], default='USD', max_length=10, verbose_name='currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('state', models.CharField(choices=[('Success', 'Success'), ('Not_Accepted', 'Not Accepted'), ('Under_Review', 'Under Review')], default='Under_Review', max_length=50, verbose_name='State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
