# Generated by Django 4.2.4 on 2023-09-12 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0008_internaltransfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('currency', models.CharField(choices=[('USDT', 'Usdt'), ('USD', 'Usd'), ('EURO', 'Euro')], max_length=10, verbose_name='currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='internaltransfers',
            name='behalf',
            field=models.CharField(default=1, max_length=10, verbose_name='Behalf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internaltransfers',
            name='description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('currency', models.CharField(choices=[('USDT', 'Usdt'), ('USD', 'Usd'), ('EURO', 'Euro')], max_length=10, verbose_name='currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('tx_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tx_id')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('destination_account_owner', models.CharField(max_length=200, verbose_name='destination_account_owner')),
                ('behalf', models.CharField(max_length=100, verbose_name='Behalf')),
                ('description', models.TextField(verbose_name='Description')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.balances', verbose_name='balance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
