# Generated by Django 4.2.5 on 2023-09-13 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0009_balances_internaltransfers_behalf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balances',
            old_name='to_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='balance',
        ),
        migrations.AddField(
            model_name='internaltransfers',
            name='destination_account_owner',
            field=models.CharField(default=1, max_length=200, verbose_name='destination_account_owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balances',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount'),
        ),
    ]
