# Generated by Django 4.2.5 on 2023-09-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_rename_to_user_balances_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='public_key',
            field=models.CharField(default=1, max_length=500, unique=True, verbose_name='public_key'),
            preserve_default=False,
        ),
    ]
