# Generated by Django 4.2.5 on 2023-09-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_wallets_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='network',
            field=models.CharField(default='TRC20', max_length=500, verbose_name='Network'),
        ),
    ]
