# Generated by Django 4.2.5 on 2023-09-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0012_wallets_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeposit',
            name='state',
            field=models.CharField(choices=[('current', 'Current'), ('completed', 'Completed'), ('failed', 'Failed')], default='current', max_length=50, verbose_name='State'),
        ),
    ]
