# Generated by Django 4.2.4 on 2023-09-17 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0013_alter_createdeposit_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('to_address', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=500)),
                ('tx_id', models.CharField(max_length=500, unique=True)),
                ('time', models.CharField(max_length=500)),
                ('email_is_sent', models.BooleanField(default=False)),
                ('from_address', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('Success', 'Success'), ('Not_Accepted', 'Not Accepted'), ('Under_Review', 'Under Review')], default='Success', max_length=50, verbose_name='State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wage',
            name='deposit_wage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Transfer_wage'),
        ),
        migrations.CreateModel(
            name='EmailBalance',
            fields=[
                ('emailloan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markets.emailloan')),
            ],
            options={
                'abstract': False,
            },
            bases=('markets.emailloan',),
        ),
    ]
