# Generated by Django 4.2.4 on 2023-09-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0014_deposithistory_emailloan_wage_deposit_wage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposithistory',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Transfer_wage'),
        ),
    ]
