# Generated by Django 4.2.4 on 2023-09-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0015_deposithistory_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaltransfers',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Transfer_wage'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Transfer_wage'),
        ),
    ]
