# Generated by Django 4.2.5 on 2023-09-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0016_internaltransfers_wage_withdrawal_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='wallets',
            name='tx_id_activation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='tx_id_activation'),
        ),
    ]
