# Generated by Django 4.2.5 on 2023-09-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0017_wallets_is_active_wallets_tx_id_activation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='is_active',
        ),
    ]
