# Generated by Django 4.2.5 on 2023-09-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('markets', '0019_blockfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockfee',
            name='reason_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Reason_content_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockfee',
            name='reason_object_id',
            field=models.CharField(default=1, max_length=50, verbose_name='Reason_object_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockfee',
            name='tx_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tx_id'),
        ),
        migrations.AlterField(
            model_name='blockfee',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('TO_ACT', 'To Act'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('TO_ACT', 'To Act'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
    ]
