# Generated by Django 4.2.5 on 2023-09-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0020_blockfee_reason_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Loan_amount'),
        ),
    ]
