# Generated by Django 4.2.5 on 2023-09-26 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0022_alter_loan_installment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('fee_limtt', models.IntegerField(editable=False, verbose_name='Fee_limit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntermediateWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_Deleted')),
                ('private_key', models.CharField(max_length=500, unique=True, verbose_name='private_key')),
                ('address', models.CharField(max_length=500, unique=True, verbose_name='address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='deposithistory',
            name='wage',
        ),
        migrations.RemoveField(
            model_name='wage',
            name='deposit_wage',
        ),
    ]
