# Generated by Django 4.2.5 on 2023-11-07 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0023_feelimit_intermediatewallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='wallets',
            name='public_key',
        ),
        migrations.AlterField(
            model_name='wallets',
            name='tx_id_activation',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='tx_id_activation'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
