# Generated by Django 4.2.5 on 2023-11-07 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0024_remove_wallets_private_key_remove_wallets_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='tx_id_activation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='tx_id_activation'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
