# Generated by Django 4.2.5 on 2023-09-12 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 2, 58, 16, 584659, tzinfo=datetime.timezone.utc), verbose_name='Birthday'),
        ),
    ]
