# Generated by Django 4.2.4 on 2023-09-12 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 8, 35, 40, 11090, tzinfo=datetime.timezone.utc), verbose_name='Birthday'),
        ),
    ]
