# Generated by Django 4.2.4 on 2023-09-17 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_usermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 9, 17, 6, 36, 35, 420426, tzinfo=datetime.timezone.utc), verbose_name='Birthday'),
        ),
    ]
