# Generated by Django 4.2.4 on 2023-09-17 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_usermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 9, 17, 7, 9, 21, 403090, tzinfo=datetime.timezone.utc), verbose_name='Birthday'),
        ),
    ]
