# Generated by Django 4.2.5 on 2023-09-22 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_usermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 5, 18, 26, 668485, tzinfo=datetime.timezone.utc), verbose_name='Birthday'),
        ),
    ]
