# Generated by Django 4.2.5 on 2023-09-25 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_usermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 23, 1, 15, 548641, tzinfo=datetime.timezone.utc), verbose_name='Birthday'),
        ),
    ]
