# Generated by Django 4.2.5 on 2023-09-26 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_usermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(default=datetime.date(1992, 10, 10), verbose_name='Birthday'),
        ),
    ]
